application: nightwingthegame
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /gameOptions
  static_dir: gameOptions
  
- url: /clues
  static_dir: clues
  
- url: /.*
  script: picapic.app
  
libraries:
- name: jinja2
  version: latest